# Generated by Django 6.0.5 on 2026-06-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                ("content", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True, default="")),
                ("category", models.CharField(blank=True, max_length=100)),
                ("published", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published"],
            },
        ),
    ]
